### ISSUE TITLE
Admin cannot change adopter email

### ISSUE THREAD

**Issue by s3526562a** [CarelleR/ProgrammingProjectOUA_2023_SP3_Team2#184]
Sprint 5 TC4.05 Admin - Update Adopter profile

Updating an Adopter's email address does not update the database and therefore does not allow the new email to log in.

When changing the email and clicking the Verify new email button, the email is received and the link works by opening a new browser windows and showing the Email verified page.
However, the database is not updated and the new email cannot login.

Returning to the Admin user and looking at the Adopter profile again, the email has not been changed.

**Comment by ary-na** [comment]
@s3526562a Hey Andrew, this is because we changed the update email code only to work when the Adopter or Shelter user is logged in to fix the security issues that codeQL picked up. So, to test this, After sending the email using the admin account, you must log out from the admin account and log into the adopter or shelter user you want to update the email. And then click on the verify email link.

**Comment by s3526562a** [comment]
Thanks @ary-na , I will go and re-test this now to verify.

**Comment by s3526562a** [comment]
@ary-na , it's still not changing the email in the database after clicking the verify email link in the email received.

**Comment by s3526562a** [comment]
Or is there a time delay perhaps and I am being impatient

**Comment by s3526562a** [comment]
Hang on, I might have missed a step.

**Comment by s3526562a** [comment]
Ok, all good, got it now. Email updaetd is being updated after I have logged into the Adopter account.

Issue resolved.
