### ISSUE TITLE
Admin cannot change shelter email

### ISSUE THREAD

**Issue by s3526562a** [CarelleR/ProgrammingProjectOUA_2023_SP3_Team2#185]
Sprint 5 TC4.06 Admin - Update Shelter profile

Updating an Shelters email address does not update the database and therefore does not allow the new email to log in.

When changing the email and clicking the Verify new email button, the email is received and the link works by opening a new browser windows and showing the Email verified page.
However, the database is not updated and the new email cannot login.

Returning to the Admin user and looking at the Shelter profile again, the email has not been changed.

**Comment by ary-na** [comment]
@s3526562a Hey Andrew, this is because we changed the update email code only to work when the Adopter or Shelter user is logged in to fix the security issues that codeQL picked up. So, to test this, After sending the email using the admin account, you must log out from the admin account and log into the adopter or shelter user you want to update the email. And then click on the verify email link.

**Comment by s3526562a** [comment]
Thanks @ary-na , I will go and re-test this now to verify.

**Comment by CarelleR** [comment]
Do you think in the email that we send to people to verify the change, we should say that the user must be logged in before they click the link? I feel that this could be a non-standard convention, so instructions could help?

**Comment by ary-na** [comment]
Yeah sure, I'll update the email content to mention this.

**Comment by CarelleR** [comment]
Additionally, from the admin's perspective, should the success messages for updating an email and password be re-worded to "the user's" instead of "your" wording. E.g., "your passwords has been updated" makes no sense for the admin when they do this for other users as it's not their account. So maybe a check to see if it's the admin's profile/login or not

**Comment by ary-na** [comment]
Sure, no worries will update the success message as well on both of them

**Comment by s3526562a** [comment]
Issue resolved after restesting based on @ary-na comments above.
